stages:
    -test
    -build

unit test:
    stage: test
    script: 
          - echo "test"
linter:
    stage: test
    script: 
          - echo "test"
build:
    stage: build
    script: 
          - ./build.sh
