stages:
  - build
  - test

image: node:18.20.4

install_dependencies:
  stage: build
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules
  cache:
    key:
      files:
        - yarn.lock
    paths:
        - node_modules
        
test:
  stage: test
  script:
    - CI = True yarn test
    
